name: imagekit
description: Imagekit package for uploading
version: 0.0.2
repository: https://github.com/nstack-in/imagekit.git
homepage: https://www.nstack.in/

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  http: ^0.13.5
